from __future__ import annotations

import re


EXIT_OK = 0
EXIT_ERROR = 1
EXIT_USAGE = 2

REQUIRED_TOOLS = ("rg", "rga", "trufflehog")
OPTIONAL_OCR_TOOLS = ("tesseract", "ocrmypdf", "pdftotext", "exiftool")
ARCHIVE_EXTENSIONS = {".zip", ".7z", ".tar", ".gz", ".tgz", ".bz2", ".xz", ".rar"}
TEXT_EXTENSIONS = {
    ".txt",
    ".md",
    ".cfg",
    ".conf",
    ".config",
    ".cnf",
    ".log",
    ".ini",
    ".json",
    ".yaml",
    ".yml",
    ".csv",
    ".properties",
    ".prop",
    ".toml",
    ".xml",
    ".env",
    ".tf",
    ".tfvars",
}
OCR_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp"}
OCR_PDF_EXTENSIONS = {".pdf"}
SENSITIVE_FILENAMES = {
    ".env": ("credential", "high"),
    ".env.local": ("credential", "high"),
    ".env.production": ("credential", "high"),
    ".env.development": ("credential", "high"),
    ".env.test": ("credential", "high"),
    ".env.staging": ("credential", "high"),
    ".env.aws": ("credential", "high"),
    ".env.azure": ("credential", "high"),
    ".env.gcp": ("credential", "high"),
    ".env.secret": ("credential", "high"),
    ".env.secrets": ("credential", "high"),
    ".env.prod": ("credential", "high"),
    ".envrc": ("credential", "high"),
    "id_rsa": ("sensitive-file", "critical"),
    "id_dsa": ("sensitive-file", "critical"),
    "id_ecdsa": ("sensitive-file", "critical"),
    "id_ed25519": ("sensitive-file", "critical"),
    "credentials.txt": ("credential", "high"),
    "secrets.txt": ("credential", "high"),
    "config.ovpn": ("sensitive-file", "medium"),
    "appsettings.json": ("credential", "medium"),
    "appsettings.production.json": ("credential", "medium"),
    "appsettings.development.json": ("credential", "medium"),
    "application.properties": ("credential", "medium"),
    "application.yml": ("credential", "medium"),
    "application.yaml": ("credential", "medium"),
    "bootstrap.yml": ("credential", "medium"),
    "bootstrap.yaml": ("credential", "medium"),
    "web.config": ("credential", "medium"),
    "app.config": ("credential", "medium"),
    "settings.ini": ("credential", "medium"),
    "settings.xml": ("credential", "medium"),
    "database.yml": ("credential", "high"),
    "datasource.xml": ("credential", "high"),
    "credentials.xml": ("credential", "high"),
    "authentication.xml": ("credential", "high"),
    "authorization.xml": ("credential", "high"),
    "connection.xml": ("credential", "high"),
    "credentials.json": ("credential", "high"),
    "service-account.json": ("credential", "high"),
    "adc.json": ("credential", "high"),
    "gcp-key.json": ("credential", "high"),
    "terraform.tfvars": ("credential", "high"),
    "terraform.tfvars.json": ("credential", "high"),
    "terraform.tfstate": ("credential", "high"),
    "terraform.tfstate.backup": ("credential", "high"),
    ".vault": ("credential", "high"),
    ".git-credentials": ("credential", "high"),
    ".gitconfig": ("credential", "medium"),
    ".netrc": ("credential", "high"),
    ".npmrc": ("credential", "high"),
    ".pypirc": ("credential", "high"),
    "pip.conf": ("credential", "high"),
    "pip.ini": ("credential", "high"),
    "nuget.config": ("credential", "high"),
    "sitemanager.xml": ("credential", "high"),
    "recentservers.xml": ("credential", "high"),
    "winscp.ini": ("credential", "high"),
    "vpn.conf": ("credential", "medium"),
    "openvpn.conf": ("credential", "medium"),
    "authorized_keys": ("sensitive-file", "high"),
    "private.key": ("sensitive-file", "critical"),
    "server.key": ("sensitive-file", "critical"),
    "client.key": ("sensitive-file", "critical"),
    "tls.key": ("sensitive-file", "critical"),
    "certificate.pem": ("sensitive-file", "high"),
    "keystore.jks": ("sensitive-file", "high"),
    "kubeconfig": ("credential", "high"),
}
SENSITIVE_PATH_SUFFIXES = {
    ".aws/credentials": ("credential", "high"),
    ".aws/config": ("credential", "medium"),
    ".azure/accesstokens.json": ("credential", "high"),
    ".azure/azureprofile.json": ("credential", "medium"),
    ".azure/az.json": ("credential", "medium"),
    ".kube/config": ("credential", "high"),
    ".docker/config.json": ("credential", "medium"),
}
SENSITIVE_EXTENSIONS = {
    ".pem": ("sensitive-file", "high"),
    ".ppk": ("sensitive-file", "high"),
    ".pfx": ("sensitive-file", "high"),
    ".p12": ("sensitive-file", "high"),
    ".p7b": ("sensitive-file", "medium"),
    ".p7c": ("sensitive-file", "medium"),
    ".cer": ("sensitive-file", "medium"),
    ".crt": ("sensitive-file", "medium"),
    ".der": ("sensitive-file", "medium"),
    ".jks": ("sensitive-file", "high"),
    ".keystore": ("sensitive-file", "high"),
    ".kdb": ("sensitive-file", "high"),
    ".kdbx": ("sensitive-file", "high"),
    ".pbk": ("credential", "medium"),
    ".ovpn": ("sensitive-file", "medium"),
    ".psafe3": ("credential", "high"),
}
KEYWORD_RULES = {
    "password": ("credential", "high", 0.95),
    "iban": ("financial-data", "medium", 0.7),
    "bsn": ("personal-data", "medium", 0.7),
}
SIGNAL_PATTERNS: tuple[tuple[re.Pattern[str], tuple[str, str, float]], ...] = (
    (
        re.compile(r"\b(?:flag|bonus|idek|bi0sCTF|EQCTF|icc)\{[^}\s]{3,120}\}", re.IGNORECASE),
        ("challenge-flag", "high", 0.98),
    ),
    (re.compile(r"\bpassword\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\bpasswords\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\bpasscode\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\bpassphrase\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:[\w-]*wachtwoord|wachtwoorden)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\btoegangscode\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(passwd|pwd)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:mot de passe|motdepasse|mot_de_passe|code d'accès|code secret)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:passwort|passwörter|kennwort|geheimnis)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:contraseña|contrasena|clave de acceso|clave)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:senha|palavra-passe|codigo de acesso)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:hasło|haslo|heslo|jelszó|jelszo|parola|adgangskode|kodeord|lösenord|losenord|passord|salasana)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(?:şifre|sifre|пароль|κωδικός|κωδικός πρόσβασης|كلمة المرور|كلمه المرور|رمز المرور|סיסמה|رمز عبور|گذرواژه|पासवर्ड|कूटशब्द|密码|密碼|口令|登录密码|登入密碼|パスワード|비밀번호|암호|kata sandi|katasandi|sandi|laluan|mật khẩu|mat khau|รหัสผ่าน)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b(secret|client_secret)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\bshared(?:[ _-]?)secret\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\baws_secret_access_key\b", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\b[\w-]*token\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\b(?:login|credential|credentials|inloggegevens|aanmeldgegevens|identifiants|zugangsdaten|anmeldedaten|credenciales|credenziali|credenciais|dane logowania|poświadczenia|prihlasovaci udaje|prihlasovacie udaje|bejelentkezési adatok|date de autentificare|loginoplysninger|inloggningsuppgifter|innloggingsinformasjon|kirjautumistiedot|giriş bilgileri|учетные данные|учётные данные|облікові дані|بيانات الاعتماد|פרטי התחברות|認証情報|ログイン情報|로그인 정보|thông tin đăng nhập|ข้อมูลเข้าสู่ระบบ)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\b(?:gebruikersnaam|username|user(?:name)?|login user)\b\s*[:=]", re.IGNORECASE), ("credential", "medium", 0.75)),
    (re.compile(r"\bapi[_-]?key(?:[_-]value)?\b\s*[:=]?", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\b[a-z][a-z0-9]{1,24}_api_[A-Za-z0-9_!.-]{6,}\b", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\b(?:pass|passphrase|secretkey|secret_key|db_password|database_password|mysql_password|postgres_password|oracle_password|sa_password|admin_password|root_password|login_password|user_password|api_secret|consumer_secret|private_key|access_key|access_token|refresh_token|auth_token|bearer_token)\b\s*[:=]", re.IGNORECASE), ("credential", "high", 0.95)),
    (re.compile(r"\bbearer\s+[A-Za-z0-9._-]+", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\bset-cookie\b.*\bhttponly\b", re.IGNORECASE), ("credential", "high", 0.9)),
    (re.compile(r"\biban\b", re.IGNORECASE), ("financial-data", "medium", 0.7)),
    (re.compile(r"\bbsn\b", re.IGNORECASE), ("personal-data", "medium", 0.7)),
    (re.compile(r"-----BEGIN [A-Z ]+PRIVATE KEY-----"), ("sensitive-file", "critical", 0.99)),
    (re.compile(r"\bopenssh private key\b", re.IGNORECASE), ("sensitive-file", "critical", 0.98)),
)
SIGNAL_PATTERN_LABELS = (
    "pattern:flag-artifact",
    "pattern:password-assignment",
    "pattern:passwords-assignment",
    "pattern:passcode-assignment",
    "pattern:passphrase-assignment",
    "pattern:wachtwoord-assignment",
    "pattern:toegangscode-assignment",
    "pattern:passwd-assignment",
    "pattern:french-password-assignment",
    "pattern:german-password-assignment",
    "pattern:spanish-password-assignment",
    "pattern:portuguese-password-assignment",
    "pattern:multilingual-password-assignment",
    "pattern:global-password-assignment",
    "pattern:secret-assignment",
    "pattern:shared-secret-assignment",
    "pattern:aws-secret-access-key",
    "pattern:token-assignment",
    "pattern:credentials-assignment",
    "pattern:username-assignment",
    "pattern:api-key",
    "pattern:api-token-value",
    "pattern:credential-field-assignment",
    "pattern:bearer-token",
    "pattern:set-cookie-httponly",
    "pattern:iban-keyword",
    "pattern:bsn-keyword",
    "pattern:private-key-block",
    "pattern:openssh-private-key",
)
DOC_NOISE_FILENAMES = {
    "license",
    "license.txt",
    "license.md",
    "readme",
    "readme.txt",
    "readme.md",
    "contributing.md",
    "copying",
    "notice",
    "notice.txt",
}
NOISE_PHRASES = (
    "capture the flag",
    "mit license",
    "copyright",
    "please see individual challenges",
    "can you find",
    "hint:",
)
NOISE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\b(?:password|passwd|pwd|wachtwoord)\b\s*[:=]\s*(?:notused|changeme|password123|test1234)\b", re.IGNORECASE),
    re.compile(r"\b(?:retired|deprecated|legacy only)\b", re.IGNORECASE),
)
SEVERITY_ORDER = {"critical": 4, "high": 3, "medium": 2, "low": 1}
ANSI_RESET = "\033[0m"
ANSI_COLORS = {
    "critical": "\033[1;31m",
    "high": "\033[31m",
    "medium": "\033[33m",
    "low": "\033[36m",
    "ok": "\033[32m",
    "warning": "\033[33m",
    "info": "\033[36m",
}
NON_FATAL_WARNING_PREFIXES = (
    "agent planning failed:",
    "agent summary failed:",
    "agent refinement failed:",
    "Ollama response repair failed:",
    "Ollama response did not include the required JSON keys.",
)
